CREATE TABLE bidding (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    customername VARCHAR(255) NOT NULL,
    itemsubject VARCHAR(255) NOT NULL,
    body VARCHAR(255) NOT NULL,
    status VARCHAR(255) DEFAULT 'Available' ,
    price INTEGER,
    numbid INTEGER DEFAULT 0,
    winner VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE attachment (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    filename VARCHAR(255) DEFAULT NULL,
    content_type VARCHAR(255) DEFAULT NULL,
    content BLOB DEFAULT NULL,
    bidding_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (bidding_id) REFERENCES bidding(id) 
);
